### PR TITLE
Sl6 support

### PR DESCRIPTION
**Pull request by pelacables**
The client package in SL6 has different name. I've added a case statement based on lsbmajdistrelease. I've tested it and works client/server.
Also, I've added a note about dependencies (MySQL and Apache).

I was not able to run tests because it install latest versions of puppet(4.0), hiera(2.0) and facter.

### CODE REVIEW

**Comment by arioch** [comment]
Could you rebase that to a single commit with a more descriptive commit message?

**Comment by arioch** [comment]
Also the version shouldn't matter.
If it doens't work on a particular version combo it's a bug.

Which is why I use TravisCI among other things.
https://travis-ci.org/arioch/puppet-ocsinventory/builds/59724140

**Comment by pelacables** [comment]
Hi,
that is because I lest SL6 packages in the default and the spec file was not modified according to that. I've left packages from CentOS 7 as default and test should run.
Please, let me rebase and try to run test myself.
Sorry for the noise.
Cheers,

**Comment by arioch** [comment]
There's no need to apologise. :)
Looks good to me so far. I'll merge when you're done. :+1:

**Pull request closed without merging**
